image: gitpod/workspace-full

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
    - ms-toolsai.jupyter@2023.9.100
    - eamodio.gitlens
    - ms-azuretools.vscode-docker
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-toolsai.vscode-jupyter-cell-tags
    - ms-toolsai.vscode-jupyter-slideshow